### ISSUE TITLE
[Bug] - When Flipper is enabled on IOS some translations are missing in MercadoPago Checkout

### ISSUE THREAD

**Issue by JonatanSalas** [BlackBoxVision/react-native-mercadopago-px#12]
## Expected Behavior

When the app is running in IOS in debug mode, and Flipper is enabled, the MercadoPago checkout should be loaded fully and correctly. 

## Current Behavior

For some reason, when we run the app in IOS in debug mode and Flipper is also enabled, some MercadoPago translations don't load correctly, and you see the translation key.

**Comment by dibermudez** [comment]
Hello, I have the same issue also when running the app in release mode on iOS. Any suggestion welcome.
Thank you!

**Comment by JonatanSalas** [comment]
@dibermudez i recommend you to go on with **v0.4.0** by running: 

- `npm i --save-dev @blackbox-vision/react-native-mercadopago-px@0.4.0`

 Also follow the README instructions from here: 

- https://github.com/BlackBoxVision/react-native-mercadopago-px/tree/v0.4.0

I'll be working on this issue as soon as possible to fix in newer versions. It seems to be a trouble related to how the Pods are getting installed.

**Comment by JonatanSalas** [comment]
We've added a section in our docs in how to workaround the following issue, until we can't it solved by the library itself. 

https://github.com/BlackBoxVision/react-native-mercadopago-px#in-ios-when-running-app-in-debugrelease-some-strings-are-missing
