### ISSUE TITLE
library not found for -lCheckoutMercadoPagoModule

### ISSUE THREAD

**Issue by emmanuel91** [BlackBoxVision/react-native-mercadopago-px#15]
hi 
i get this  erro when try compile  a ios project.

i am new in ios develpment ,  maybe  i dont follow the instructions correctly

thanks for you help

[pod1.zip](https://github.com/BlackBoxVision/react-native-mercadopago-px/files/4942036/pod1.zip)

atach the pod file

**Comment by JonatanSalas** [comment]
Hi @emmanuel91,

If you don't provide me enough information I can't help to solve your issue.

**Comment by JonatanSalas** [comment]
@emmanuel91 closing this issue, because reading the title, this seems referred to the older library we've. That library is currently deprecated, and we don't have intention to give support.
