### ISSUE TITLE
Question, What does exactly MP Checkout includes?

### ISSUE THREAD

**Issue by cesarcgfg** [BlackBoxVision/react-native-mercadopago-px#17]
Hi, Maybe a silly question.

But, what does MP Checkout includes? 
only credit card payments? 
Cash (payment in stores ) ?
Bank transfer
etc

Thank you!

**Comment by JonatanSalas** [comment]
It really depends on what you want, it supports practically all the payment methods you've asked for. 

The checkout interacts with MP API to get data from a Preference ID: 

- https://www.mercadopago.com.ar/developers/es/reference/preferences/_checkout_preferences/post/

I'm closing this issue as this isn't currently related to the library itself.
