### ISSUE TITLE
Checkout failing on every payment result

### ISSUE THREAD

**Issue by fedetoledo** [BlackBoxVision/react-native-mercadopago-px#18]
**Describe the bug**
I'm having this problem.  When you press "pagar", it says "procesando pago" and after that, the "pagar"  button goes unavailable, and an empty red square slides up for a second, no text within. After that I can't pay again, I have to go back to my app.

EDIT:
I'm using the example code that you provide. I have created a Mercado Pago test user and using it as a customer, while using my sandbox credentials to test the integration. It could be misconfiguration, as i'm testing in Android and couldn't find the installation process, like the IOS manual installation in your docs. I used automatic link but would be great to check if it's all linked like it should. 

**Screenshots**
![Screenshot_20200801-124833](https://user-images.githubusercontent.com/37426772/89105240-d7d91d80-d3f5-11ea-8985-7f30521051a2.png)
![Screenshot_20200801-124836](https://user-images.githubusercontent.com/37426772/89105242-dad40e00-d3f5-11ea-9378-eba84cbf9b95.png)

**Smartphone**
 - Device: [Motorola Moto G Play]
 - OS: [Anrdoid 7.1.1]

**Comment by JonatanSalas** [comment]
Hi! Thanks for reaching us. 

We need a little bit of information to understand what's going on around, so let's check a few steps: 

1.  How are you dealing with the Checkout Preference creation?
2. The Checkout Preference that you're creating is in sandbox mode or production mode?
3. The Credentials that you're using to launch the Mobile Checkout is in sandbox mode or production mode? 

I think that the problem could be related for a misconfiguration. If you're creating a preference that doesn't match correctly with your credentials, or if you're mixing environments when dealing with the checkout this error is pretty common.

**Comment by fedetoledo** [comment]
Thanks for the reply, I've updated the issue.

**Comment by JonatanSalas** [comment]
In react-native at version superior to v0.60 dependencies are auto-linked. 

This library started with react-native 0.60 in mind. For IOS we've a little bit more steps, due to issues with how MP needs the integration to be done. 

Maybe for this case, would be cool to get access to the repo so we can help you understand what's going on. 

If you've your repo hosted here, bring me access! Glad to help you.

**Comment by fedetoledo** [comment]
Sent you invitation. I have added the official mercado pago dependency to my android build, maybe that's bringing up some issues with the setup.

**Comment by JonatanSalas** [comment]
You shouldn't add that! Our library covers you with MP, we've installed in gradle library setup the latest working version of MP. 

You can see it here:

https://github.com/BlackBoxVision/react-native-mercadopago-px/blob/master/android/build.gradle#L130

**Comment by fedetoledo** [comment]
Ok, the error is not from this library, but from my testing user from MP. Using any random email like "user@test.com" works perfectly. Thank you for your help!

**Comment by JonatanSalas** [comment]
You're welcome! Glad to help!
