### ISSUE TITLE
Enable Flipper

### ISSUE THREAD

**Issue by jdnichollsc** [BlackBoxVision/react-native-mercadopago-px#2]
You can enable Flipper by using this plugin from your Podfile https://github.com/joncardasis/cocoapods-user-defined-build-types

```
plugin 'cocoapods-user-defined-build-types'

enable_user_defined_build_types!

pod 'MercadoPagoSDK', :build_type => :dynamic_framework
```

Regards

**Comment by JonatanSalas** [comment]
Interesting! I'll check it out! Thanks!

**Comment by JonatanSalas** [comment]
Moving to newer issue -> https://github.com/BlackBoxVision/react-native-mercadopago-px/issues/5
