### ISSUE TITLE
Error in production mode, when paying with cash

### ISSUE THREAD

**Issue by aleluis777** [BlackBoxVision/react-native-mercadopago-px#20]
good morning my query is that in development mode the system works correctly. but in production mode it only accepts credit cards but does not pay cash as "PagoEfectivo"

**To Reproduce**

- Use the production access.
-  use this data to generate the id

items:[
				{
					id:userid,
					title,description,quantity,currency_id,unit_price,
					category_id:{}
				}],
			payer: {
				email:String,
				phone: String,
				name: Sstringe,
				surname: String,
			},
			notification_url:url,
============================Return Post.data==============================
{
  additional_info: '',
  auto_return: '',
  back_urls: { failure: '', pending: '', success: '' },
  binary_mode: false,
  client_id: '**ggggg**',
  collector_id: **777777777**,
  coupon_code: null,
  coupon_labels: null,
  date_created: '2020-08-18T04:51:52.143+00:00',
  date_of_expiration: null,
  expiration_date_from: null,
  expiration_date_to: null,
  expires: false,
  external_reference: '',
  id: '**xxxxxx-xxxxxxxx-9d8xxxxxxxxxxb-xxx-xxx-xxxxxxx'**,
  init_point: 'https://www.mercadopago.com.pe/checkout/v1/redirect?pref_id=**xxxxxxxx-xxxxxxxxx',**
  internal_metadata: null,
  items: [
    {
      id: '23',
      category_id: '{"type":"tema","productId":22}',
      currency_id: 'PEN',
      description: 'Liderazgo Integral',
      title: 'Liderazgo Integral',
      quantity: 1,
      unit_price: 100
    }
  ],
  marketplace: 'NONE',
  marketplace_fee: 0,
  metadata: {},
  notification_url: 'https://api.xxxxxx.com/client/.........
  operation_type: 'regular_payment',
  payer: {
    phone: { area_code: '', number: **'99999999999'** },
    address: { zip_code: '', street_name: '', street_number: null },
    email: '**lxxxxxxxx**@gmail.com',
    identification: { number: '', type: '' },
    name: '**xxxxxxxxxxx**',
    surname: '**xxxxxxxxxxx**',
    date_created: null,
    last_purchase: null
  },
  payment_methods: {
    default_card_id: null,
    default_payment_method_id: null,
    excluded_payment_methods: [ [Object] ],
    excluded_payment_types: [ [Object] ],
    installments: null,
    default_installments: null
  },
  processing_modes: null,
  product_id: null,
  redirect_urls: { failure: '', pending: '', success: '' },
  sandbox_init_point: 'https://sandbox.mercadopago.com.pe/checkout/v1/redirect?pref_id=**xxxxxxxxxxxxxxxxxxxx**',
  site_id: 'MPE',
  shipments: {
    default_shipping_method: null,
    receiver_address: {
      zip_code: '',
      street_name: '',
      street_number: null,
      floor: '',
      apartment: '',
      city_name: null,
      state_name: null,
      country_name: null
    }
  },
  total_amount: null,
  last_updated: null
}

**Expected behavior**
Is it perhaps some data that I have to send in the POST ???? or configure my Mercadopago account ???
![image](https://user-images.githubusercontent.com/24797816/90473366-5f0ddd00-e0e8-11ea-9ed8-0ded47f0cce3.png)
image  PRODUCTION MODE (KEY AND TOKEN)

When I use the card payment it works correctly. payment proceeds.

When I generate the ticket to make the payment with PagoEfectivo (In development mode, TEST-TOKEN AND TEST-KEY) it works. the only problem is in development mode.
![image](https://user-images.githubusercontent.com/24797816/90473814-6da8c400-e0e9-11ea-97b0-97b4be6c6bff.png)
Image TEST MODE (KEY AND TOKEN)

**Comment by JonatanSalas** [comment]
@aleluis777 It seems that there's a trouble related to MercadoPago API, checkout this issue: https://github.com/mercadopago/px-android/issues/2235
