### ISSUE TITLE
 IOS installation problems

### ISSUE THREAD

**Issue by aleluis777** [BlackBoxVision/react-native-mercadopago-px#25]
**Describe the bug**
Use of 'min' refers to instance method rather than global function 'min' in module 'Swift' FOLDER LMBUSSINESCOMPONENT)

**To Reproduce**
1. Good Make all the previous configurations as shown in the repository.
2. when running pod install everything is correct., but then it throws me an error when I give it in react-native run-ios

ERROR:--->**The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.2.99**

I could solve this error by modifying the podfile:
![Captura de Pantalla 2020-09-25 a la(s) 22 42 27](https://user-images.githubusercontent.com/24797816/94329411-701bfa80-ff80-11ea-8c13-3c9bf65ab668.png)

but then when I rerun the react-native run-ios command I got a second error

**error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening Braindtic.xcworkspace.**
![Captura de Pantalla 2020-09-25 a la(s) 22 48 01](https://user-images.githubusercontent.com/24797816/94329502-2d0e5700-ff81-11ea-9ca2-3e346214e892.png)

I solved that problem by entering xcode and compiling the program from there. the problem is that this works with the example from the repository. but not when I create a new project.

The error when I create the new project from scratch is the following
![Captura de Pantalla 2020-09-25 a la(s) 22 48 54](https://user-images.githubusercontent.com/24797816/94329524-4c0ce900-ff81-11ea-9d76-fcd5c8cc342c.png)
![Captura de Pantalla 2020-09-25 a la(s) 22 49 20](https://user-images.githubusercontent.com/24797816/94329530-5b8c3200-ff81-11ea-85b1-42693c3fc8cd.png)
Rute error.

![Captura de Pantalla 2020-09-25 a la(s) 22 54 06](https://user-images.githubusercontent.com/24797816/94329601-06045500-ff82-11ea-9a91-faaafd221291.png)

Using: XCODE 12.0
React native 0.63.2

**Comment by manutuero** [comment]
Hi @aleluis777, thanks for your report!

We're going to check this issue during the weekend.

Do yo have any repo that we can review?. If not, we'll be creating another one with react native 0.63.2. Cheers!

**Comment by aleluis777** [comment]
> Hola @ aleluis777 , ¡gracias por tu informe!
> 
> Revisaremos este problema durante el fin de semana.
> 
> ¿Tiene algún repositorio que podamos revisar? Si no, crearemos otro con react native 0.63.2. ¡Salud!

Yes: https://github.com/aleluis777/TestMP

**Comment by JonatanSalas** [comment]
Hi @aleluis777, did you manage to solve the issue? We have been with tons of work, might check it this weekend maybe.

**Comment by aleluis777** [comment]
my solution was to use your example folder and from there create my project

**Comment by JonatanSalas** [comment]
Closing the issue since it's already fixed.
