### ISSUE TITLE
Create Preference (Sandbox)

### ISSUE THREAD

**Issue by jdnichollsc** [BlackBoxVision/react-native-mercadopago-px#3]
Solo por curiosidad, sabrás como crear bien la preferencia en modo Sandbox? No he dejado de tener este error https://github.com/mercadopago/px-ios/issues/2233

**Comment by JonatanSalas** [comment]
No se puntualmente contra que te estás integrando, pero, en la documentación ellos especifican este cURL como forma para generar la preferencia. 

```bash
curl -X POST \
    'https://api.mercadopago.com/checkout/preferences?access_token=ACCESS_TOKEN' \
    -H 'Content-Type: application/json' \
    -d '{
      "items": [
        {
          "title": "Dummy Item",
          "description": "Multicolor Item",
          "quantity": 1,
          "currency_id": "ARS",
          "unit_price": 10.0
        }
      ],
      "payer": {
        "email": "payer@email.com"
      }
    }'
```

`ACCESS_TOKEN` es el token que tenes en las credenciales asociadas a tu aplicación para el modo sandbox. Usando ese `ACCESS_TOKEN` deberías de poder generar una preferencia correctamente

**Comment by jdnichollsc** [comment]
Si me crea la preferencia, pero a la hora de empezar el mobile checkout me sale ese error 🤔

**Comment by JonatanSalas** [comment]
Cómo te estás integrando para lanzar el checkout de MercadoPago, estás con nuestra librería o estás usando otra?

**Comment by jdnichollsc** [comment]
Probando esta librería también, estoy preguntando por si habían probado en Modo Sandbox, porque en la documentación dicen crear usuarios de pruebas, uno como comprador y otro como vendedor, pero siempre me sale esto a la hora de probar el mobile checkout en iOS

**Comment by JonatanSalas** [comment]
Fijate en el ejemplo que desarrollamos, básicamente lo que tenes que hacer es desde tu cuenta de MercadoPago crear una aplicación, MercadoPago te va a dar las credenciales de Sandbox y tenes que usar eso para levantar la preferencia. 

Podes ver un poco más el ejemplo que armamos: 

https://github.com/BlackBoxVision/react-native-mercadopago-px/tree/master/example

**Comment by jdnichollsc** [comment]
Si, esas son las que estoy usando, igual cierro este issue porque es un problema que estoy teniendo con MercadoPago, pero gracias por tu tiempo!

**Comment by JonatanSalas** [comment]
Éxitos en la resolución del issue!

**Comment by jdnichollsc** [comment]
@JonatanSalas creo que sería bueno sugerir en el README que se debe de crear la preferencia de pago desde el backend por seguridad, para no exponer desde la app ese access token :)

**Comment by JonatanSalas** [comment]
Totalmente! De hecho lo teníamos, estamos trabajando en otros ejemplos más real like.
