### ISSUE TITLE
Comenzar a usar Mercado Pago Px

### ISSUE THREAD

**Issue by MartinUgarte** [BlackBoxVision/react-native-mercadopago-px#34]
Hola. Siempre me he dedicado a hacer Front-end en React Native pero nunca hice Back-end asi que disculpen por mi ignorancia. Seguí todos los pasos de instalación y requisitos previos. Estoy utilizando el Example Usage en una screen dentro de mi aplicación llamada **MercadoPagoTest.js** y la copie y pegué tal cual como está escrito. Posteriormente creé un archivo llamado **react-native-config.env** dentro de la carpeta "react-native-mercadopago-px" y dentro coloque:

`#.env
MP_ACCESS_TOKEN= el access token de mi usuario de prueba creado con Postman
MP_PUBLIC_KEY= el public key de mi usuario de prueba creado con Postman`

Luego en **MercadoPagoTest.js** cambie las partes que dicen 'payer@email.com' por el mail de mi usuario de prueba. En ningún momento utilice curl (no sé como utilizarlo). Al colocar npm run android la consola me tira el error: 

**Execution failed for task ':blackbox-vision_react-native-mercadopago-px:packageDebugResources'**

Desearia saber que estoy haciendo mal o como solucionar ese error. Desde ya muchisimas gracias.

Martin.

Adjunto mis scripts:
https://pastebin.com/JKmqDM6k
https://pastebin.com/uXDUy3j5

**Comment by JonatanSalas** [comment]
@MartinUgarte cómo estás? Tenes algún repo para mostrarnos como lo configuraste y poder ayudarte?

**Comment by MartinUgarte** [comment]
Si, aquí esta: https://github.com/MartinUgarte/Test

Te paso las credenciales de mi usuario de prueba: https://pastebin.com/b5zU226T

Muchas gracias!

**Comment by JonatanSalas** [comment]
Ahí lo reviso y te tiro un centro!

**Comment by JonatanSalas** [comment]
@MartinUgarte como para darte un consejo por temas de seguridad, no grabes esas API Keys en pastebin, por lo que vi los tokens que publicaste son los productivos, no son de prueba. Los APP_USER son los tokens de MP de producción, los TEST_USER son para el ambiente de staging. 

También están el client ID y el secret. Tene cuidado con eso, de hecho te diría que hasta borres la imagen que subiste acá a la issue.

**Comment by JonatanSalas** [comment]
No pude correr `npm run android` por un bardo con `services.gradle.org` pero corri el mismo comando que implica `react-native run-android` que es `gradle app:installDebug -PreactNativeDevServerPort=8081` y me funciono el build sin ningún problema:

<img width="1270" alt="android build" src="https://user-images.githubusercontent.com/7697196/111459354-579fc800-86f9-11eb-8e01-4544738a1064.png">

**Comment by JonatanSalas** [comment]
@MartinUgarte si queres probate hacer un `cd android && ./gradlew clean` y después hacer `npm run android`. Yo no pude reproducir el issue.

**Comment by MartinUgarte** [comment]
Buenas tardes, muchas gracias por responderme. Creé un proyecto nuevo y estoy corriéndolo en un emulador. Estoy utilizando una parte del código de ejemplo para probar la parte de checkout y harcodeé una preferencia. Ahora me abre la pestaña de MercadoPago pero me pone error. Aquí adjunto lo único que hice.

En el POST puse el access token de un usuario de prueba vendedor, y puse como mail de payer el correo del usuario de prueba comprador. Con eso genere el preferenceId y lo volqué en el código principal. Coloque en Public Key del usuario comprador. ¿Qué debería corregir? Saludos!

![Duda1](https://user-images.githubusercontent.com/39602138/111545449-d9710f00-8754-11eb-9882-b557d94f1d13.png)
![Duda2](https://user-images.githubusercontent.com/39602138/111545453-db3ad280-8754-11eb-9b72-24c15245bcf9.png)

**Comment by JonatanSalas** [comment]
@MartinUgarte la publicKey tiene que ser de la cuenta adonde va a ir a parar el dinero, tiene que matchear con la misma cuenta con la que se creo la preferencia de pago, osea, la cuenta del vendedor. 

Eso esta en el [README](https://github.com/BlackBoxVision/react-native-mercadopago-px#pre-requisites) de nuestra librería.

**Comment by MartinUgarte** [comment]
Funcionó! Mil gracias por tu ayuda. Saludos!

**Comment by JonatanSalas** [comment]
Genial, un placer poder ayudar, saludos!
