### ISSUE TITLE
Guardar Tarjetas de Crédito y Login

### ISSUE THREAD

**Issue by MartinUgarte** [BlackBoxVision/react-native-mercadopago-px#35]
Buenos días, disculpá la molestia. Quería consultar si es posible una vez ingresados los datos de la tarjeta por primera vez guardar los mismos para la próxima vez que se realiza una compra dentro de la aplicación. 

Mi otra duda es si hay alguna forma de loguearse en Mercado Pago una vez apretado el botón de "comprar" en vez de hardcodear y poner el mail del payer dentro del script. También se deberían guardar los datos de login para la próxima compra.

Muchas gracias! Espero la respuesta.

Saludos!

**Comment by JonatanSalas** [comment]
No tiene mecanismo de persistencia, el checkout corre en modo guest y no soporta autenticación. 

Podes ver más acá: https://github.com/mercadopago/px-android/issues/2322#issuecomment-691558160

**Comment by MartinUgarte** [comment]
Perfecto gracias, entonces intentaré usar el Web Tokenize Checkout con el WebView. Gracias!
