### ISSUE TITLE
Problema al obtener el pago

### ISSUE THREAD

**Issue by avaromatias** [BlackBoxVision/react-native-mercadopago-px#49]
Buenas, estoy usando la librería y todo funciona correctamente salvo por una diferencia que encuentro cuando realizo un pago a través de la web que brinda MercadoPago.

- Si realizo el pago desde la interfaz que brinda MercadoPago:
Una vez realizado el pago, cuando voy a obtener la información del mismo a la API de MercadoPago (https://api.mercadopago.com/v1/payments/{id}), me devuelve un json con los items de mi compra en "additional_info.items"

> {
>     "acquirer_reconciliation": [],
>     "additional_info": {
>         "authentication_code": null,
>         "available_balance": null,
>         "ip_address": "XXX.XXX.X.X",
>         "items": [
>             {
>                 "category_id": null,
>                 "description": "Descripcion",
>                 "id": null,
>                 "picture_url": null,
>                 "quantity": "1",
>                 "title": "Titulo",
>                 "unit_price": "300.0"
>             }
>         ],
>         "nsu_processadora": null
>     },
>     "authorization_code": null,
>     "binary_mode": false,
>     "brand_id": null,
>     "call_for_authorize_id": null,
>     "captured": true,
>     "card": {
>         "cardholder": {
>             "identification": {
>                 "number": "XXXXXXXX",
>                 "type": "DNI"
>             },
>             "name": "APRO"
>         },
>         "date_created": "2021-07-23T13:15:16.000-04:00",
>         "date_last_updated": "2021-07-23T13:15:16.000-04:00",
>         "expiration_month": 11,
>         "expiration_year": 2025,
>         "first_six_digits": "450995",
>         "id": null,
>         "last_four_digits": "3704"
>     },
>     "charges_details": [],
>     "collector_id": 130685343,
>     "corporation_id": null,
>     "counter_currency": null,
>     "coupon_amount": 0,
>     "currency_id": "ARS",
>     "date_approved": "2021-07-23T13:15:16.963-04:00",
>     "date_created": "2021-07-23T13:15:16.857-04:00",
>     "date_last_updated": "2021-07-23T13:15:16.963-04:00",
>     "date_of_expiration": null,
>     "deduction_schema": "PROACTIVE_3",
>     "description": "Descripcion",
>     "differential_pricing_id": null,
>     "external_reference": null,
>     "fee_details": [
>         {
>             "amount": 7.23,
>             "fee_payer": "collector",
>             "type": "mercadopago_fee"
>         }
>     ],
>     "id": 1239029852,
>     "installments": 1,
>     "integrator_id": null,
>     "issuer_id": "310",
>     "live_mode": false,
>     "marketplace_owner": null,
>     "merchant_account_id": null,
>     "merchant_number": null,
>     "metadata": {},
>     "money_release_date": "2021-08-27T13:15:16.963-04:00",
>     "money_release_schema": null,
>     "notification_url": null,
>     "operation_type": "regular_payment",
>     "order": {
>         "id": "2993569680",
>         "type": "mercadopago"
>     },
>     "payer": {
>         "first_name": null,
>         "last_name": null,
>         "email": "test_user_80507629@testuser.com",
>         "identification": {
>             "number": "XXXXXXXX",
>             "type": "DNI"
>         },
>         "phone": {
>             "area_code": null,
>             "number": null,
>             "extension": null
>         },
>         "type": null,
>         "entity_type": null,
>         "id": "795845222"
>     },
>     "payment_method_id": "visa",
>     "payment_type_id": "credit_card",
>     "platform_id": null,
>     "point_of_interaction": {},
>     "pos_id": null,
>     "processing_mode": "aggregator",
>     "refunds": [],
>     "shipping_amount": 0,
>     "sponsor_id": null,
>     "statement_descriptor": "XXXXXX",
>     "status": "approved",
>     "status_detail": "accredited",
>     "store_id": null,
>     "taxes_amount": 0,
>     "transaction_amount": 300,
>     "transaction_amount_refunded": 0,
>     "transaction_details": {
>         "acquirer_reference": null,
>         "external_resource_url": null,
>         "financial_institution": null,
>         "installment_amount": 300,
>         "net_received_amount": 292.77,
>         "overpaid_amount": 0,
>         "payable_deferral_period": null,
>         "payment_method_reference_id": null,
>         "total_paid_amount": 300
>     }
> }

- Si realizo el pago desde la librería react-native-mercadopago-px:
Una vez realizado el pago, cuando voy a obtener la información del mismo a la API de MercadoPago (https://api.mercadopago.com/v1/payments/{id}), no me devuelve los items (ni la ip_address, entre otros, aunque por el momento no me interesan esos datos).

> {
>     "acquirer_reconciliation": [],
>     "additional_info": {
>         "authentication_code": null,
>         "available_balance": null,
>         "nsu_processadora": null
>     },
>     "authorization_code": null,
>     "binary_mode": false,
>     "brand_id": null,
>     "call_for_authorize_id": null,
>     "captured": true,
>     "card": {
>         "cardholder": {
>             "identification": {
>                 "number": "XXXXXXXX",
>                 "type": "DNI"
>             },
>             "name": "APRO"
>         },
>         "date_created": "2021-07-23T13:13:52.000-04:00",
>         "date_last_updated": "2021-07-23T13:13:52.000-04:00",
>         "expiration_month": 11,
>         "expiration_year": 2025,
>         "first_six_digits": "503175",
>         "id": null,
>         "last_four_digits": "0604"
>     },
>     "charges_details": [],
>     "collector_id": 130685343,
>     "corporation_id": null,
>     "counter_currency": null,
>     "coupon_amount": 0,
>     "currency_id": "ARS",
>     "date_approved": "2021-07-23T13:13:52.977-04:00",
>     "date_created": "2021-07-23T13:13:52.867-04:00",
>     "date_last_updated": "2021-07-23T13:13:52.977-04:00",
>     "date_of_expiration": null,
>     "deduction_schema": "PROACTIVE_3",
>     "description": "Descripcion",
>     "differential_pricing_id": null,
>     "external_reference": null,
>     "fee_details": [
>         {
>             "amount": 7.23,
>             "fee_payer": "collector",
>             "type": "mercadopago_fee"
>         }
>     ],
>     "id": 1239031297,
>     "installments": 1,
>     "integrator_id": null,
>     "issuer_id": "3",
>     "live_mode": false,
>     "marketplace_owner": null,
>     "merchant_account_id": null,
>     "merchant_number": null,
>     "metadata": {},
>     "money_release_date": "2021-08-27T13:13:52.977-04:00",
>     "money_release_schema": null,
>     "notification_url": null,
>     "operation_type": "regular_payment",
>     "order": {},
>     "payer": {
>         "first_name": null,
>         "last_name": null,
>         "email": "test_user_80507629@testuser.com",
>         "identification": {
>             "number": "XXXXXXXX",
>             "type": "DNI"
>         },
>         "phone": {
>             "area_code": null,
>             "number": null,
>             "extension": null
>         },
>         "type": null,
>         "entity_type": null,
>         "id": "795845222"
>     },
>     "payment_method_id": "master",
>     "payment_type_id": "credit_card",
>     "platform_id": null,
>     "point_of_interaction": {},
>     "pos_id": null,
>     "processing_mode": "aggregator",
>     "refunds": [],
>     "shipping_amount": 0,
>     "sponsor_id": null,
>     "statement_descriptor": "PRINCE",
>     "status": "approved",
>     "status_detail": "accredited",
>     "store_id": null,
>     "taxes_amount": 0,
>     "transaction_amount": 300,
>     "transaction_amount_refunded": 0,
>     "transaction_details": {
>         "acquirer_reference": null,
>         "external_resource_url": null,
>         "financial_institution": null,
>         "installment_amount": 300,
>         "net_received_amount": 292.77,
>         "overpaid_amount": 0,
>         "payable_deferral_period": null,
>         "payment_method_reference_id": null,
>         "total_paid_amount": 300
>     }
> }

Quería saber si a alguien más le ha pasado o si estoy haciendo algo mal.
Saludos y muchas gracias.

**Comment by JonatanSalas** [comment]
@avaromatias eso tiene que ver más quizás con una diferencia en la creación de la preferencia para el pago que de nuestra librería en sí. 

Nuestro SDK utiliza las UI de MP y las integra desde react-native en una forma fácil de usar, todo lo que tiene que ver respecto a los datos usados para la inicialización del SDK se handlea en el backend, mediante la generación de la preferencia del pago.

**Comment by amoyano** [comment]
@JonatanSalas  hola, por que siempre me trae first name y lastname null? hay forma de obtener esos datos?

**Comment by mnofresno** [comment]
Tengo la misma duda que @amoyano cómo me traigo el name y los datos del local o de la persona que recibe la transferencia?
