### ISSUE TITLE
Error while bundling 

### ISSUE THREAD

**Issue by luchux** [BlackBoxVision/react-native-mercadopago-px#56]
**Describe the bug**
Gradle fails to bundle package. 

**To Reproduce**
1. start any empty react-native projects 
2. run `npm i @blackbox-vision/react-native-mercadopago-px` as explained in https://react-native-mercadopago-px.blackbox-vision.tech/docs/install
3. run-android fails with gradle error: 
`error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.mercadopago.android.px:checkout:4.45.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/mercadopago/android/px/checkout/4.45.0/checkout-4.45.0.pom
       - file:/Users/luchux/.m2/repository/com/mercadopago/android/px/checkout/4.45.0/checkout-4.45.0.pom
       - file:/Users/luchux/Devel/compartir/node_modules/react-native/android/com/mercadopago/android/px/checkout/4.45.0/checkout-4.45.0.pom
       - file:/Users/luchux/Devel/compartir/node_modules/jsc-android/dist/com/mercadopago/android/px/checkout/4.45.0/checkout-4.45.0.pom
       - https://dl.google.com/dl/android/maven2/com/mercadopago/android/px/checkout/4.45.0/checkout-4.45.0.pom
       - https://www.jitpack.io/com/mercadopago/android/px/checkout/4.45.0/checkout-4.45.0.pom
     Required by:
         project :app > project :blackbox-vision_react-native-mercadopago-px

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

    at makeError (/Users/luchux/Devel/compartir/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
    at /Users/luchux/Devel/compartir/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (/Users/luchux/Devel/compartir/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:106:5)
    at async Command.handleAction (/Users/luchux/Devel/compartir/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
`
**Expected behavior**
gradle should build well. 

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Dependencies**
Add the name and version of all dependencies of your project.

**Comment by JonatanSalas** [comment]
@luchux would you mind to create a repo for case reproduction? I'm not able to replicate the issue from our example application in the library.

**Comment by luchux** [comment]
Ok Will try again with a blank new project and see what happens.
Cheers.

**Comment by JonatanSalas** [comment]
@luchux thanks! let me know if it works, and if it doesn't work please share to me the repo so I can lookup and find a fix for it!

**Comment by danieldbo** [comment]
Hello @JonatanSalas @luchux I have a same error, how I can fix it? Thanks
