### ISSUE TITLE
 [TypeError: null is not an object (evaluating '_reactNative.NativeModules.ReactNativeMercadopagoPx.createPayment')]

### ISSUE THREAD

**Issue by Rusbelllozano** [BlackBoxVision/react-native-mercadopago-px#57]
**Describe the bug**
Hola, estoy intentando realizar la integracion segun las indicaciones, pero esta arrojando este error
Como podria solucionar este error?
**Screenshots**
<img width="522" alt="Captura de pantalla 2021-11-24 a las 10 07 13 a  m" src="https://user-images.githubusercontent.com/16036663/143263236-614a340a-5e04-47d9-a705-6667b2c58e9a.png">
<img width="591" alt="Captura de pantalla 2021-11-24 a las 10 04 07 a  m" src="https://user-images.githubusercontent.com/16036663/143262789-e687ecad-ac42-4ec6-8829-0c13188bf3de.png">

**Additional context**
"react-native": "0.61.5",
 "@blackbox-vision/react-native-mercadopago-px": "^0.7.2",

**Comment by Rusbelllozano** [comment]
Despues de leer, pienso que lo que sucede es que no encuentra en NativeModules la clase ReactNativeMercadopagoPx,  pero, como podria hacerlo funcionar?


<img width="698" alt="Captura de pantalla 2021-11-25 a las 4 31 45 p  m" src="https://user-images.githubusercontent.com/16036663/143501451-fcf12daa-c4b3-41ce-b1c6-1cb5b3f27ec6.png">

**Comment by JonatanSalas** [comment]
Buenas, podrías indicar un poco de info sobre como estás laburando? 

- Sistema Operativo
- Entorno de React Native
- Es una aplicación Expo?

Tenemos puesto un template de bug report en los issues que buscamos que nos completen, porque con info al aire nunca vamos a poder determinar como ayudar a resolver el problema, cuanto más contexto des sobre el problema que tenes, más fácil va a ser ayudarte.

**Comment by Rusbelllozano** [comment]
Hola @JonatanSalas,
SO : MacOs 11.52
Version de react
No es una aplicacion expo
`{
  "name": "appEnlau",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "postinstall": "jetifier -r",
    "reload": "adb shell input text \"RR\"",
    "menu-dev": "adb shell input keyevent 82",
    "build-android": "cd android/ && ./gradlew bundleRelease && cd .."
  },
  "dependencies": {
    "@blackbox-vision/react-native-mercadopago-px": "^0.7.2",
    "@invertase/react-native-apple-authentication": "^1.1.2",
    "@kesha-antonov/react-native-action-cable": "^1.0.5",
    "@react-native-community/datetimepicker": "^2.1.0",
    "@react-native-community/google-signin": "^3.0.2",
    "@react-native-community/toolbar-android": "^0.2.1",
    "@sentry/react-native": "^1.0.9",
    "axios": "^0.19.0",
    "currency-formatter": "^1.5.5",
    "formik": "^1.5.8",
    "i18n-js": "^3.3.0",
    "moment": "^2.24.0",
    "react": "16.9.0",
    "react-moment": "^0.9.6",
    "react-native": "0.61.5",
    "react-native-code-push": "^6.1.0",
    "react-native-device-info": "^4.0.1",
    "react-native-fbsdk": "^1.1.1",
    "react-native-firebase": "~5.5.6",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-image-picker": "^1.1.0",
    "react-native-intercom": "^13.1.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-modal": "^11.4.0",
    "react-native-phone-input": "0.2.1",
    "react-native-picker-select": "^6.3.3",
    "react-native-reanimated": "^1.3.0",
    "react-native-safe-area-context": "^0.6.4",
    "react-native-safe-area-view": "^1.0.0",
    "react-native-screens": "1.0.0-alpha.23",
    "react-native-shadow": "^1.2.2",
    "react-native-snap-carousel": "^3.8.2",
    "react-native-svg": "^9.11.1",
    "react-native-switch-selector": "^2.0.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-walkthrough-tooltip": "^1.1.3",
    "react-native-webview": "^8.1.2",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.9.4",
    "react-navigation-tabs": "^2.5.6",
    "react-redux": "^7.2.0",
    "redux": "^4.0.4",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0",
    "rn-content-loader": "^0.0.4",
    "yup": "^0.27.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.4",
    "@babel/runtime": "^7.6.3",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "babel-plugin-module-resolver": "^4.0.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "jetifier": "^1.6.4",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-devtools": "^3",
    "react-test-renderer": "16.9.0",
    "reactotron-react-native": "^4.0.2",
    "reactotron-redux": "^3.1.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
`
