### ISSUE TITLE
Null is not an object

### ISSUE THREAD

**Issue by tomaspasto24** [BlackBoxVision/react-native-mercadopago-px#73]
Hola. 
Lo instalé con yarn add y tengo mismo código del ejemplo de su página, pero aún así me tira el siguiente error 
 
![image](https://user-images.githubusercontent.com/60078552/196501409-24bec79c-8c7c-44c5-9521-9439c89046d7.png)

Paso a mostrar foto de los componentes que estoy usando:
![image](https://user-images.githubusercontent.com/60078552/196501510-2115c158-7a91-4b96-8db7-a3fd4458cc7e.png)
![image](https://user-images.githubusercontent.com/60078552/196501646-a8c556bb-9301-42cb-9a36-b05d95c18513.png)
El access token es uno generado para tests. Si pueden ayudarme les agradezco.

**Comment by JonatanSalas** [comment]
Que version de react-native estas usando? usas Expo?

**Comment by tomaspasto24** [comment]
Sí, uso expo

**Comment by JonatanSalas** [comment]
Claro, es por eso, todavia no tenemos implementado un config plugin para Expo. Tan pronto podamos lo vamos a estar haciendo, en los docs tenemos especificado el tema de la compatibilidad con Expo:

https://react-native-mercadopago-px.blackbox-vision.tech/docs/compatibility#expo

Tenes que usar expo prebuild para que te genere las carpetas de android e ios y configurarlo como un proyecto de react native tradicional siguiendo los steps que tenemos definidos en nuestras documentacion.

**Comment by tomaspasto24** [comment]
El access token y publicKey lo saque de MercadoPago cómo credenciales tests, podría venir por ahí pero me parece que debería ser otro error diferente al que me aparece

**Comment by JonatanSalas** [comment]
Quedate tranca que eso no es el problema. Basicamente ahi lo que pasa es que no te esta cargando el codigo nativo de nuestra lib. Tal como lo expreso en este [comment](https://github.com/BlackBoxVision/react-native-mercadopago-px/issues/73#issuecomment-1282781265), te recomiendo que uses [expo prebuild](https://docs.expo.dev/workflow/prebuild). Con eso vas a poder configurar la lib y usarla sin problemas.

**Comment by tomaspasto24** [comment]
Muchas gracias por la explicación. Es decir que ejecutando npx expo run:Android debería funcar?

**Comment by JonatanSalas** [comment]
De nada! Entiendo que si porque ese comando corre prebuild de fondo si no me equivoco y genera la carpeta de android. Probalo y cualquier cosas nos podes dar feedback!

**Comment by tomaspasto24** [comment]
Hice expo eject y me dio el siguiente error. Por ende desinstale el paquete y volví a hacer expo eject, para luego instalar el paquete y hacer npm run android. Pero vuelve a aparecer el error.
![image](https://user-images.githubusercontent.com/60078552/197359459-262584ee-9fff-40f0-bf0b-30bdd770d335.png)

**Comment by tomaspasto24** [comment]
![image](https://user-images.githubusercontent.com/60078552/197359490-264251dd-5349-4b98-bdce-c08ae023fbf7.png)

**Comment by JonatanSalas** [comment]
https://github.com/BlackBoxVision/react-native-mercadopago-px/issues/67#issuecomment-1250378361

**Comment by tomaspasto24** [comment]
![image](https://user-images.githubusercontent.com/60078552/197364421-d931cb88-c435-48c3-b156-2a324d0b75d9.png)
Sobre la solución propuesta, pude cambiar la versión de kotlin pero lo de agregar el link no porque no aparece el objeto AllProjects. Sigo teniendo este problema, solo con npm run android. No al hacer expo eject.

**Comment by tomaspasto24** [comment]
Es decir, build.gradle me aparece así. Como ya se encuentra el url, imagino que no tengo que volver a agregarlo
![image](https://user-images.githubusercontent.com/60078552/197364478-eeda9daa-e340-4ed5-acc0-b8540053f49d.png)

**Comment by rmarcenaro** [comment]
Hola @JonatanSalas !

Tengo el mismo problema y no estoy utilizando EXPO. Creo la Promesa sin problemas y al ejecutar _createPayment_ allí me devuelve el mismo error:
_Something went wrong null is not an object (evaluating '_reactNative.NativeModules.ReactNativeMercadopagoPx.createPayment')_

¿Me puedes ayudar?

Desde ya muchas gracias!

**Comment by JonatanSalas** [comment]
Me podras pasar mas info? Porque la realidad es que el error es uno solo, quiere decir que nativamente la biblioteca no se cargo en el build.

**Comment by rmarcenaro** [comment]
> Me podras pasar mas info? Porque la realidad es que el error es uno solo, quiere decir que nativamente la biblioteca no se cargo en el build.

Claro. ¿Qué información te paso? Así no te paso información de más que te haga perder el tiempo.
Gracias!

**Comment by rmarcenaro** [comment]
> 

Las dependencias del proyecto...
"@blackbox-vision/react-native-mercadopago-px": "^0.8.0",
    "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-native-community/datetimepicker": "^5.1.0",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.10",
    "axios": "^0.21.0",
    "moment": "^2.29.4",
    "native-base": "^2.13.14",
    "react": "16.13.1",
    "react-native": "^0.63.3",
    "react-native-animatable": "^1.3.3",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-autogrow-input": "^0.2.1",
    "react-native-dropdown-picker": "^5.4.4",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-google-places-autocomplete": "^2.0.3",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-maps": "0.27.1",
    "react-native-maps-directions": "^1.8.0",
    "react-native-motion-slider": "^1.0.3",
    "react-native-reanimated": "^1.13.1",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-screens": "^2.12.0",
    "react-native-shimmer-placeholder": "^2.0.9",
    "react-native-simple-toast": "^1.1.3",
    "react-native-vector-icons": "^7.1.0",
    "react-native-webview": "^11.26.1",
    "react-navigation": "4.2.2",
    "react-navigation-drawer": "^2.6.0",
    "react-navigation-stack": "^2.10.0",
    "react-navigation-tabs": "^2.10.1",
    "react-navigation-transitions": "^1.0.12",
    "rn-placeholder": "^3.0.3"


Va la implementación...

import MercadoPagoCheckout from '@blackbox-vision/react-native-mercadopago-px';

![image](https://user-images.githubusercontent.com/6248517/221198904-0d011a01-1072-401d-8bad-cdead1639ccb.png)

**Comment by JonatanSalas** [comment]
En que estas testeando, android o ios? En caso de ser iOS, seguiste todos los pasos adicionales de setup para iOS que estan en los docs? 🤔

**Comment by rmarcenaro** [comment]
> En que estas testeando, android o ios? En caso de ser iOS, seguiste todos los pasos adicionales de setup para iOS que estan en los docs? 🤔

Estoy en Android. Después de luchar un buen rato, finalmente, al parecer, era la configuración de Gradle que no incluía la librería en la compilación; superado eso, funcionó.
Gracias por tu tiempo!

**Comment by JonatanSalas** [comment]
Que bueno que funciona la verdad! Perdon que no pude ser de mucha ayuda, solo tirarte cual era la causa del problema. Me alegro que los hayas podido resolver! Muchos exitos!
